# Cloudflare Pages configuration
# IMPORTANT: Update the 'name' field to match your project
# - For existing projects: Use your Cloudflare Pages project name
# - For new projects: Choose a unique name (will create project-name.pages.dev)
name = "lite-paper-docs"
compatibility_date = "2025-01-14"
pages_build_output_dir = "out"

[env.production]
compatibility_date = "2025-01-14"
